version: "3"

services:
  livekit:
    build: ../../services/livekit
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "5100-6100:5100-6100"

  backend:
    build: ../../services/server
    env_file:
      - ../../services/server/.env.local
    restart: always
    depends_on:
      - livekit
    ports:
      - "5000:5000"

  frontend:
    build: ../../services/client
    env_file:
      - ../../services/client/.env.local
    restart: always
    depends_on:
      - backend
    ports:
      - "3002:3002"
