version: "3"

services: #Описываем используемые контейнеры
  backend: #Контейнер бэкенда
    build: ../../services/server #указываем путь к сервису (если у вас каталог с бэкендом называется иначе - нужно поменять)
    restart: always
    environment: #тут передаем переменные среды
      - PORT=5000
      - LK_API_URL=wss://myapp-u3u448ny.livekit.cloud
      - LK_API_KEY=API7GEjtT6ypGiS
      - LK_SECRET_KEY=xPXzFTrs4Q8OdCpYHOfj02Xc2tkL933oqMMkFVSY5Wa
    ports:
      - "5000:5000" #предполагая, что переданная выше переменная среды определяет порт процесса внутр контейнера

  frontend: #Контейнер фронтенда, рассматриваем кейс когда использовался create-react-app
    build: ../../services/client #указываем путь к сервису (если у вас каталог с фронтом назывется иначе - нужно поменять)
    restart: always
    depends_on:
      - backend
    environment: #передаем нужные переменные среды
      - NODE_ENV=production
      - VITE_PORT=3002
      - VITE_SERVER_URL=https://kurentochat-va.staging.forasoft.com
      - VITE_LK_API_URL=wss://myapp-u3u448ny.livekit.cloud
      - VITE_LK_API_KEY=API7GEjtT6ypGiS
      - VITE_LK_SECRET_KEY=xPXzFTrs4Q8OdCpYHOfj02Xc2tkL933oqMMkFVSY5Wa
    ports:
      - "3002:3002" #предполагаем что процесс внутри контейнера запущен на дефолтном для create-react-app 3000 порту
