version: "3"

services:
  backend:
    environment:
      - PORT=5000
      - LK_API_URL=wss://myapp-u3u448ny.livekit.cloud
      - LK_API_KEY=API7GEjtT6ypGiS
      - LK_SECRET_KEY=xPXzFTrs4Q8OdCpYHOfj02Xc2tkL933oqMMkFVSY5Wa
    build: ../../services/server
    restart: always
    ports:
      - "5000:5000"

  frontend:
    environment:
      - NODE_ENV=production
      - VITE_PORT=3002
      - VITE_SERVER_URL=https://genise-tk.ru
      - VITE_LK_API_URL=wss://myapp-u3u448ny.livekit.cloud
      - VITE_LK_API_KEY=API7GEjtT6ypGiS
      - VITE_LK_SECRET_KEY=xPXzFTrs4Q8OdCpYHOfj02Xc2tkL933oqMMkFVSY5Wa
    build: ../../services/client
    restart: always
    depends_on:
      - backend
    ports:
      - "3002:3002"
