version: "3"

services:
  backend:
    build: ../../services/server
    restart: always
    ports:
      - "5000:5000"

  frontend:
    build: ../../services/client
    restart: always
    depends_on:
      - backend
    ports:
      - "3002:3002"
